name: DasNarayan Opinion World Dashboard

on:
  schedule:
    - cron: '*/30 * * * *'  # Run every 30 minutes (UTC)
  workflow_dispatch:
jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Specify the Node.js version

      - name: Install dependencies
        run: npm install
        env:
          OPINION_WORLD_USERNAME: ${{ secrets.OTHER_OPINION_WORLD_USERNAME }}
          OPINION_WORLD_PASSWORD: ${{ secrets.OTHER_OPINION_WORLD_PASSWORD }}
          TELEGRAM_TOKEN: ${{ secrets.OTHER_TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.OTHER_TELEGRAM_CHAT_ID }}

      - name: Run script
        run: node index.js
        env:
          OPINION_WORLD_USERNAME: ${{ secrets.OTHER_OPINION_WORLD_USERNAME }}
          OPINION_WORLD_PASSWORD: ${{ secrets.OTHER_OPINION_WORLD_PASSWORD }}
          TELEGRAM_TOKEN: ${{ secrets.OTHER_TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.OTHER_TELEGRAM_CHAT_ID }}
